name: Publish Library

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:

jobs:
  publish:
    uses: catalis-vc/cicd/.github/workflows/build-maven.yaml@main
    with:
      java-version: '21'
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}