name: Publish to GitHub Packages

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-and-publish:
    uses: catalis-vc/cicd/.github/workflows/build-maven.yaml@main
    with:
      java-version: "21"
      skip-tests: false
    secrets:
      PAT_GITHUB_PACKAGES: ${{ secrets.PAT_GITHUB_PACKAGES }}